/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PrimerParcial.Actividad1.SegundaAtividad;

import javax.swing.JOptionPane;

/**
 * @author isaac
 */
public class Actividad2 extends javax.swing.JFrame {

    /**
     * Creates new form Actividad2
     */
    public Actividad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnMostrar = new javax.swing.JMenu();
        btnMuestra = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnEditar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnPreguntar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnPersonaliza = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));

        btnMostrar.setText("Mostrar mensaje");

        btnMuestra.setText("Mostrar");
        btnMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuestraActionPerformed(evt);
            }
        });
        btnMostrar.add(btnMuestra);

        jMenuBar1.add(btnMostrar);

        jMenu2.setText("Editar");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jMenu2.add(btnEditar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Preguntar");

        btnPreguntar.setText("Preguntar");
        btnPreguntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntarActionPerformed(evt);
            }
        });
        jMenu3.add(btnPreguntar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Personalizar");

        btnPersonaliza.setText("Personaliza");
        btnPersonaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalizaActionPerformed(evt);
            }
        });
        jMenu4.add(btnPersonaliza);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String hola = JOptionPane.showInputDialog(rootPane, "Digite lo que quiera");
        JOptionPane.showMessageDialog(rootPane, hola);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuestraActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Este mensaje de prueba solo se le muestra al usuario", "Hola", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnMuestraActionPerformed

    private void btnPreguntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(rootPane, "Este mensaje solo es para mostrarte si te queda claro esto", "Pregunta",
                JOptionPane.YES_NO_CANCEL_OPTION);
    }//GEN-LAST:event_btnPreguntarActionPerformed

    private void btnPersonalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalizaActionPerformed
        // TODO add your handling code here:
        //crea una ventana de ejemplo de JOtionPane.OptionPane
        Object[] options = {"Si", "No", "Cancelar"};
        int n = JOptionPane.showOptionDialog(rootPane,
                "¿Desea guardar los cambios?",
                "Guardar",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[2]);


    }//GEN-LAST:event_btnPersonalizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnEditar;
    private javax.swing.JMenu btnMostrar;
    private javax.swing.JMenuItem btnMuestra;
    private javax.swing.JMenuItem btnPersonaliza;
    private javax.swing.JMenuItem btnPreguntar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
