/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

/**
 *
 * @author viejo
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInformacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnReglaFalsa = new javax.swing.JButton();
        btnBabilonico = new javax.swing.JButton();
        btnBiseccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jPanel2.setBackground(new java.awt.Color(255, 138, 132));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Metodos Numericos");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 30, 240, 30);

        btnInformacion.setBackground(new java.awt.Color(255, 138, 132));
        btnInformacion.setText("Informacion");
        btnInformacion.setToolTipText("Informacion del proyecto");
        btnInformacion.setBorder(null);
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnInformacion);
        btnInformacion.setBounds(700, 40, 100, 19);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1200, 100);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Elige el Metodo ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 170, 220, 30);

        btnReglaFalsa.setText("Regla Falsa");
        btnReglaFalsa.setBorder(null);
        btnReglaFalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReglaFalsaActionPerformed(evt);
            }
        });
        getContentPane().add(btnReglaFalsa);
        btnReglaFalsa.setBounds(550, 280, 100, 30);

        btnBabilonico.setText("Babilonico");
        btnBabilonico.setBorder(null);
        btnBabilonico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBabilonicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBabilonico);
        btnBabilonico.setBounds(90, 280, 100, 30);

        btnBiseccion.setText("Biseccion");
        btnBiseccion.setBorder(null);
        btnBiseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiseccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnBiseccion);
        btnBiseccion.setBounds(320, 280, 100, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void btnBabilonicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBabilonicoActionPerformed
        // TODO add your handling code here:
        //se abre la ventana de Babilonico y se oculta esta
        Babilonico b = new Babilonico();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBabilonicoActionPerformed

    private void btnBiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiseccionActionPerformed
        // TODO add your handling code here:
        //se abre la ventana de Biseccion y se oculta esta
        Biseccion b = new Biseccion();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBiseccionActionPerformed

    private void btnReglaFalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReglaFalsaActionPerformed
        // TODO add your handling code here:
        //se abre la ventana de Regla Falsa y se oculta esta
        ReglaFalsa r = new ReglaFalsa();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReglaFalsaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBabilonico;
    private javax.swing.JButton btnBiseccion;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnReglaFalsa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
