/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SegundoParcial.tercerapractica;

import javax.swing.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.*;
import java.util.ArrayList;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author isaac
 */
public class OrdenamientoAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form OrdenamientoAlumnos
     */
    public OrdenamientoAlumnos() {
        initComponents();
        
    }
    private javax.swing.JComboBox<String> comboxAlumno;
    private javax.swing.JLabel LabelAlumno;
    private javax.swing.JComboBox<String> comboboxmaestro;
    private javax.swing.JLabel lblmaestro;




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCargarAlumnos = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnNuevaencuesta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jMenu1.setText("Archivo");

        btnCargarAlumnos.setText("Cargar Alumnos");
        btnCargarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(btnCargarAlumnos);

        btnSalir.setText("Salir");
        jMenu1.add(btnSalir);

        btnNuevaencuesta.setText("Nueva encuentas ");
        btnNuevaencuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaencuestaActionPerformed(evt);
            }
        });
        jMenu1.add(btnNuevaencuesta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edicion");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarAlumnosActionPerformed
        // TODO add your handling code here:
        javax.swing.JComboBox<String> comboBoxalumnos;
        comboBoxalumnos = new javax.swing.JComboBox<>();

        // leer archivo Alumnos.txt
        File archivo = new File("/home/isaac/Universidad/Programacion Visual/unedl_PV_2024A/src/SegundoParcial/tercerapractica/Alumnos.txt");

        // Initialize an ArrayList to store the names of the students
        ArrayList<String> Estudiantes = new ArrayList<>();

        try {
            BufferedReader br = new BufferedReader(new FileReader(archivo));
            String linea;
            while((linea = br.readLine()) != null){
                // Add each line (student's name) to the ArrayList
                Estudiantes.add(linea);
            }
            br.close();
        } catch (Exception e) {
            System.out.println("Error al leer archivo");
        }

        //ordena los nombres de los alumnos por orden alfabetico
        Estudiantes.sort(String::compareToIgnoreCase);



        //manda al combobox los nombres de los alumnos
        comboBoxalumnos.setModel(new javax.swing.DefaultComboBoxModel<>(Estudiantes.toArray(new String[0])));
        getContentPane().add(comboBoxalumnos);
        comboBoxalumnos.setBounds(100, 80, 250, 25);

        //se crean un boton que diga nuevo
        javax.swing.JButton btnNuevo = new javax.swing.JButton("Nuevo");
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(100, 120, 250, 25);

        //se crea un evento para el boton "nuevo"
        btnNuevo.addActionListener(e -> {
            //se esconde el boton nuevo
            btnNuevo.setVisible(false);
            //se crean un txtfield para el nombre y un boton para guardar
            javax.swing.JTextField txtNombre = new javax.swing.JTextField();
            getContentPane().add(txtNombre);
            txtNombre.setBounds(100, 160, 250, 25);

            javax.swing.JButton btnGuardar = new javax.swing.JButton("Guardar");
            getContentPane().add(btnGuardar);
            btnGuardar.setBounds(100, 200, 250, 25);

            //se crea un evento para el boton "guardar"
            btnGuardar.addActionListener(e2 -> {
                //se añade el nombre al combobox si el campo de texto no está vacío
                String nombreCompleto = txtNombre.getText();
                String[] partesNombre = nombreCompleto.split(" ");
                if (partesNombre.length >= 3) {
                    boolean valid = true;
                    for (String parte : partesNombre) {
                        if (parte.length() < 3 || !parte.matches("[a-zA-Z]+")) {
                            valid = false;
                            break;
                        }
                    }
                    if (valid) {
                        Estudiantes.add(nombreCompleto);
                        //se ordena el combobox
                        Estudiantes.sort(String::compareToIgnoreCase);
                        comboBoxalumnos.setModel(new javax.swing.DefaultComboBoxModel<>(Estudiantes.toArray(new String[0])));
                        //se manda el estudiante al archivo
                        try {
                            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo, true));
                            bw.write(nombreCompleto);
                            bw.newLine();
                            bw.close();
                        } catch (Exception e3) {
                            System.out.println("Error al escribir en archivo");
                        }
                    } else {
                        // Mostrar un mensaje de error si el campo de texto no cumple con el formato
                        JOptionPane.showMessageDialog(null, "Cada parte del nombre (nombre y apellidos) debe tener al menos tres letras y solo contener letras", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    // Mostrar un mensaje de error si el campo de texto no cumple con el formato
                    JOptionPane.showMessageDialog(null, "Debe ingresar al menos un nombre y dos apellidos", "Error", JOptionPane.ERROR_MESSAGE);
                }
                //se esconde el txtfield y el boton guardar
                txtNombre.setVisible(false);
                btnGuardar.setVisible(false);
                //se muestra el boton nuevo
                btnNuevo.setVisible(true);
            });


        });


    }//GEN-LAST:event_btnCargarAlumnosActionPerformed

    private void btnNuevaencuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaencuestaActionPerformed
        // TODO add your handling code here:


        LabelAlumno = new javax.swing.JLabel();
        comboxAlumno = new javax.swing.JComboBox<>();
        
        LabelAlumno.setText("Seleccione el alumno que realizara la encuetas");
        getContentPane().add(LabelAlumno);
        LabelAlumno.setBounds(10, 20, 260, 50);

       //se crea un arraylist para guardar los nombres de los alumnos
        ArrayList<String> alumnos = new ArrayList<>();
        //se añade un espacio en blanco al principio
        alumnos.add("");
        //se lee el archivo de alumnos
        File archivo = new File("/home/isaac/Universidad/Programacion Visual/unedl_PV_2024A/src/SegundoParcial/tercerapractica/Alumnos.txt");
        try {
            BufferedReader br = new BufferedReader(new FileReader(archivo));
            String linea;
            while((linea = br.readLine()) != null){
                //se añaden los nombres al arraylist
                alumnos.add(linea);
            }
            br.close();
        } catch (Exception e) {
            System.out.println("Error al leer archivo");
        }
        //se ordenan los nombres de los alumnos
        alumnos.sort(String::compareToIgnoreCase);

        //se añaden los nombres al combobox
        comboxAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(alumnos.toArray(new String[0])));
        getContentPane().add(comboxAlumno);
        comboxAlumno.setBounds(10, 70, 260, 25);


        //se hace una accion para el combobox
        comboxAlumno.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedItem = (String)e.getItem();
                    if (!selectedItem.isEmpty()) {

                        //se crea un lbl que dice el nombre de alumno
                        javax.swing.JLabel lblAlumno = new javax.swing.JLabel();
                        lblAlumno.setText("Alumno seleccionado: " + selectedItem);
                        getContentPane().add(lblAlumno);
                        lblAlumno.setBounds(10, 100, 260, 25);

                        //se ocultan el combobox y el lbl
                        comboxAlumno.setVisible(false);
                        LabelAlumno.setVisible(false);


                        // Aquí puedes agregar el código que se ejecutará cuando se seleccione un nombre
                        lblmaestro = new javax.swing.JLabel();
                        comboboxmaestro = new javax.swing.JComboBox<>();
                        
                        lblmaestro.setText("Seleccione maestro a evaluar");
                        getContentPane().add(lblmaestro);
                        lblmaestro.setBounds(30, 40, 210, 19);

                   // Creación de un nuevo objeto JSONParser para analizar el contenido de un archivo JSON.
                    JSONParser parser = new JSONParser();

                    try {
                        // Lectura y análisis del archivo JSON ubicado en la ruta especificada.
                        Object obj = parser.parse(new FileReader("/home/isaac/Universidad/Programacion Visual/unedl_PV_2024A/src/SegundoParcial/tercerapractica/DocenTes.json"));

                        // Conversión del objeto analizado a un objeto JSONObject.
                        JSONObject jsonObject = (JSONObject) obj;

                        // Extracción del array JSON "Docentes" del objeto JSONObject.
                        JSONArray docentes = (JSONArray) jsonObject.get("Docentes");

                        // Creación de un ArrayList para almacenar los nombres de los maestros.
                        ArrayList<String> maestros = new ArrayList<>();

                        // Adición de un espacio en blanco al principio de la lista de maestros.
                        maestros.add("");

                        // Iteración sobre cada objeto en el array JSON "Docentes".
                        for(Object docenteObj : docentes){
                            // Conversión del objeto a un objeto JSONObject.
                            JSONObject docente = (JSONObject) docenteObj;

                            // Extracción del valor de la clave "Nombre" del objeto JSONObject.
                            String nombre = (String) docente.get("Nombre");

                            // Adición del nombre del maestro a la lista de maestros.
                            maestros.add(nombre);
                        }

                        // Ordenación de la lista de maestros en orden alfabético (ignorando las diferencias de mayúsculas y minúsculas).
                        maestros.sort(String::compareToIgnoreCase);

                        // Configuración del modelo del JComboBox "comboboxmaestro" con los nombres de los maestros en la lista.
                        comboboxmaestro.setModel(new javax.swing.DefaultComboBoxModel<>(maestros.toArray(new String[0])));

                        // Adición del JComboBox "comboboxmaestro" al contenedor de contenido del JFrame.
                        getContentPane().add(comboboxmaestro);

                        // Establecimiento de la posición y tamaño del JComboBox "comboboxmaestro".
                        comboboxmaestro.setBounds(30, 80, 240, 25);

                        


                    } catch (Exception e1) {
                        // Impresión de un mensaje de error en la consola si ocurre alguna excepción durante la lectura o el análisis del archivo.
                        System.out.println("Error al leer archivo");
                    }

                        
                    }
                }
            }
        });
        

    }//GEN-LAST:event_btnNuevaencuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenamientoAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenamientoAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenamientoAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenamientoAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenamientoAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCargarAlumnos;
    private javax.swing.JMenuItem btnNuevaencuesta;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
