/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PrimerParcial.Actividad1;

import javax.swing.JOptionPane;

/**
 * @author isaac
 */
public class ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form ventana1
     */
    public ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnArchivos = new javax.swing.JMenu();
        btnsalir = new javax.swing.JMenuItem();
        btnEditar = new javax.swing.JMenu();
        btnAcerdaDe = new javax.swing.JMenu();
        btnVersion = new javax.swing.JMenuItem();
        btnInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("trabajo 1");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("trabajo 1"); // NOI18N
        getContentPane().setLayout(null);

        btnArchivos.setText("Archivos");

        btnsalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btnsalir.setText("salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        btnArchivos.add(btnsalir);

        jMenuBar1.add(btnArchivos);

        btnEditar.setText("Editar");
        jMenuBar1.add(btnEditar);

        btnAcerdaDe.setText("Acerca de");
        btnAcerdaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcerdaDeActionPerformed(evt);
            }
        });

        btnVersion.setText("Version");
        btnVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVersionActionPerformed(evt);
            }
        });
        btnAcerdaDe.add(btnVersion);

        btnInformacion.setText("Informacion");
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });
        btnAcerdaDe.add(btnInformacion);

        jMenuBar1.add(btnAcerdaDe);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Programa terminado", "Cierre de laventa", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVersionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Practica 1", "Aplicaciones UNEDL", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVersionActionPerformed

    private void btnAcerdaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcerdaDeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnAcerdaDeActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(rootPane, "Isaac Diaz Rodriguez, universidad ENrique Diaz De leon, Ingeneria en software", "Informacion", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAcerdaDe;
    private javax.swing.JMenu btnArchivos;
    private javax.swing.JMenu btnEditar;
    private javax.swing.JMenuItem btnInformacion;
    private javax.swing.JMenuItem btnVersion;
    private javax.swing.JMenuItem btnsalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
